# -*- coding: utf-8 -*-
"""Untitled43.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wJsPnJQSHjbgs5Vb4nFLxia4vFdJzwRm
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install pyzbar

!apt install libzbar0

from pyzbar import pyzbar
import cv2
from google.colab.patches import cv2_imshow
image = cv2.imread('/content/drive/MyDrive/Barcode-Reader/cf.png')
barcodes = pyzbar.decode(image)
for barcode in barcodes:
    (x, y, w, h) = barcode.rect
    cv2.rectangle(image, (x, y), (x + w, y + h), (255, 0, 0), 2)

    barcodeData = barcode.data.decode('utf-8')
    barcodeType = barcode.type
    text = "{} ( {} )".format(barcodeData, barcodeType)
    cv2.putText(image, text, (x, y - 10), cv2.FONT_HERSHEY_COMPLEX, 0.5, (255, 0, 0), 2)

    print("Information : \n Found Type : {} Barcode : {}".format(barcodeType, barcodeData))

cv2_imshow(image)
cv2.waitKey(0)